// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Wilco.Elections.SampleBallotLookup.Migrations
{
    [DbContext(typeof(AdminDbContext))]
    [Migration("20250410175332_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BallotStyle", b =>
                {
                    b.Property<long>("VUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("VUID"));

                    b.Property<string>("LABEL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PCT_CODE")
                        .HasColumnType("int");

                    b.HasKey("VUID");

                    b.ToTable("BallotStyles");
                });

            modelBuilder.Entity("BallotStyleLink", b =>
                {
                    b.Property<int>("StyleCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StyleCode"));

                    b.Property<int>("PrecinctID")
                        .HasColumnType("int");

                    b.Property<string>("QALink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SplitID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StyleCode");

                    b.ToTable("BallotStyleLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
