// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Wilco.Elections.SampleBallotLookup.Migrations
{
    [DbContext(typeof(AdminDbContext))]
    partial class AdminDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BallotStyle", b =>
                {
                    b.Property<long>("VUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("VUID"));

                    b.Property<string>("LABEL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PCT_CODE")
                        .HasColumnType("int");

                    b.HasKey("VUID");

                    b.ToTable("BallotStyles");
                });

            modelBuilder.Entity("BallotStyleLink", b =>
                {
                    b.Property<int>("StyleCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StyleCode"));

                    b.Property<int>("PrecinctID")
                        .HasColumnType("int");

                    b.Property<string>("QALink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SplitID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StyleCode");

                    b.ToTable("BallotStyleLinks");
                });

            modelBuilder.Entity("Voter", b =>
                {
                    b.Property<long>("VUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("VUID"));

                    b.Property<string>("ADCITY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADNUM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADPARCEL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADPREFIX")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADST")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADSTR1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADSTR2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADSTYPE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADSUFFIX")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADUNIT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADUTYPE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADZIP4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADZIP5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CD_DIST_TYPE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CITY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COMM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DASSIGNMENT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DEFFECTED")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DESIG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DTBALLOT")
                        .HasColumnType("datetime2");

                    b.Property<string>("FAX")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FBDELIVERY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FL_AD_OVERSEAS")
                        .HasColumnType("bit");

                    b.Property<string>("FPARTY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FPCAFLAG")
                        .HasColumnType("bit");

                    b.Property<string>("GENDER")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HISPANIC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MADCITY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MADNUM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MADST")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MADSTR1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MADSTR2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MADUNIT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MADZIP4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MADZIP5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MAIL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MCOUNTRY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MDESIG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MUTYPE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NB_DISTRICT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NMFIRST")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NMLAST")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NMMID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NMSUFFIX")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OTHER")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PARTY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRECINCT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RDATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("SBE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SCHOOL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SDATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("SNAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SREASON")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STATUS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STREP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STSEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SUPPRESS")
                        .HasColumnType("bit");

                    b.Property<string>("TNAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TOWNID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USREP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VUID");

                    b.ToTable("Voters");
                });
#pragma warning restore 612, 618
        }
    }
}
